### ISSUE TITLE
[1.8.8] Crash with glass shards 1.5.2

### ISSUE THREAD

**Issue by ghost** [ljfa-ag/Glass-Shards#10]
Forge 1609
Glass Shards 1.5.2 for 1.8.8

Was putting a small set of 1.8.8 mods together and threw in glass and ice shards but it appears glass shards is crashing here: http://pastebin.com/Va4TJd6e

Tested with latest forge (1609) and the first forge released for 1.8.8, issues on both.

**Comment by ljfa-ag** [comment]
Okay strange...I totally tested it with 1589 and it worked before.

I recompiled it (with a newer Forgegradle version) and now it seems to be fine. No idea what was wrong there.

**Comment by ljfa-ag** [comment]
Actually no, it was the Curseforge plugin that was using the wrong artifact (jar instead of build)...that would explain everything

**Comment by ghost** [comment]
Aha! That makes a lot more sense. Glad the issue is known now at least :P

**Comment by ljfa-ag** [comment]
Yeah...I only suspected that after I just uploaded the "fixed" version using the plugin...oh well, now I had to upload it manually ^^

Reported to matthewprenger/CurseGradle#4.
