### ISSUE TITLE
Other glass shards 1.7.10

### ISSUE THREAD

**Issue by Tsyklop** [ljfa-ag/Glass-Shards#11]
I found a problem. Meta shards different from those that are needed in the recipe
![2016-09-26_00 38 37](https://cloud.githubusercontent.com/assets/6783568/18818428/dd2526b2-8381-11e6-80b1-3d489ddbc420.png)
![2016-09-26_00 38 44](https://cloud.githubusercontent.com/assets/6783568/18818429/decacfd0-8381-11e6-860a-37062ddbeb6e.png)

**Comment by ljfa-ag** [comment]
I don't understand what you mean. Does that recipe not work?
And how did you get the shards with metadata 32767? They are not supposed to have this metadata.

**Comment by Tsyklop** [comment]
Does not work the recipe, at the white shards. I do not know. Break the glass, and fell out.

**Comment by ljfa-ag** [comment]
The recipe not working with this metadata is fine, but no glass is supposed to drop that.
Did you try it without other mods?

**Comment by Tsyklop** [comment]
@ljfa-ag without other mods all fine.

**Comment by ljfa-ag** [comment]
Is this still a problem? I see no way how glass could drop shards with this metadata.

**Comment by ljfa-ag** [comment]
Closing for lack of reproducibility
