### ISSUE TITLE
Easy way to use custom item with custom glass

### ISSUE THREAD

**Issue by The-Fireplace** [ljfa-ag/Glass-Shards#8]
Could you add an easy way, in GlassType, to register a custom type of glass with a custom item to use as the shard? I have a kind of glass I would like to register that shouldn't go with any of the colors of vanilla glass.
If there is one, or an easy workaround, let me know.

**Comment by The-Fireplace** [comment]
Edit: I saw that this was added in a later version

**Comment by ljfa-ag** [comment]
For this case you would use a custom ModGlassHandler I guess.
